name: Actions_Aufgabe_1

on:
    push:
       branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    hello-world:
        runs-on: ubuntu-latest

        steps:
          - name: Repository auschecken
            uses: actions/checkout@v4

          - name: Begrüßung ausgeben
            run: echo "Hallo von GitHub Actions!"
          
          - name: Aktuelles Datum anzeigen
            run: date
        
          - name: Dateien im Repository anzeigen
            run: ls -la
        
          - name: Node.js Version anzeigen
            run: node --version

          - name: aktuellen Git Branch anzeigen
            run: git branch